# FastAPI Application Configuration

app_name = "TomlEv FastAPI Example"
version = "1.0.0"
debug = "${DEBUG|-false}"

[server]
host = "${HOST|-0.0.0.0}"
port = "${PORT|-8000}"
reload = "${RELOAD|-false}"

[api]
prefix = "/api/v1"
title = "TomlEv API"
description = "Example API using TomlEv for configuration"
docs_url = "/docs"
redoc_url = "/redoc"

[cors]
allow_origins = ["http://localhost:3000", "https://example.com"]
allow_methods = ["GET", "POST", "PUT", "DELETE"]
allow_headers = ["*"]

[database]
url = "postgresql://${DB_USER|-postgres}:${DB_PASSWORD|-password}@${DB_HOST|-localhost}:${DB_PORT|-5432}/${DB_NAME|-fastapi_db}"
pool_size = 10
max_overflow = 20

[security]
secret_key = "${SECRET_KEY}"
algorithm = "HS256"
access_token_expire_minutes = 30
